// <auto-generated />
using System;
using JustRDP.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JustRDP.Infrastructure.Migrations
{
    [DbContext(typeof(JustRdpDbContext))]
    [Migration("20260302193302_AddUsageTracking")]
    partial class AddUsageTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("JustRDP.Domain.Entities.TreeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ParentId", "SortOrder");

                    b.ToTable("TreeEntries", (string)null);

                    b.HasDiscriminator<string>("EntryType").HasValue("TreeEntry");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("JustRDP.Infrastructure.Persistence.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("JustRDP.Domain.Entities.ConnectionEntry", b =>
                {
                    b.HasBaseType("JustRDP.Domain.Entities.TreeEntry");

                    b.Property<int>("AudioRedirectionMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoReconnect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("ColorDepth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(32);

                    b.Property<bool>("Compression")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("ConnectCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("ConnectionType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("CredentialDomain")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CredentialPasswordEncrypted")
                        .HasColumnType("BLOB");

                    b.Property<string>("CredentialUsername")
                        .HasColumnType("TEXT");

                    b.Property<int>("DesktopHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DesktopWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GatewayDomain")
                        .HasColumnType("TEXT");

                    b.Property<string>("GatewayHostName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("GatewayPasswordEncrypted")
                        .HasColumnType("BLOB");

                    b.Property<int>("GatewayUsageMethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GatewayUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NetworkLevelAuthentication")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(3389);

                    b.Property<bool>("RedirectClipboard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("RedirectDrives")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RedirectPorts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RedirectPrinters")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RedirectSmartCards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResizeBehavior")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SshPrivateKeyPassphraseEncrypted")
                        .HasColumnType("BLOB");

                    b.Property<string>("SshPrivateKeyPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SshTerminalFontFamily")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double?>("SshTerminalFontSize")
                        .HasColumnType("REAL");

                    b.ToTable("TreeEntries", t =>
                        {
                            t.Property("CredentialDomain")
                                .HasColumnName("ConnectionEntry_CredentialDomain");

                            t.Property("CredentialPasswordEncrypted")
                                .HasColumnName("ConnectionEntry_CredentialPasswordEncrypted");

                            t.Property("CredentialUsername")
                                .HasColumnName("ConnectionEntry_CredentialUsername");
                        });

                    b.HasDiscriminator().HasValue("Connection");
                });

            modelBuilder.Entity("JustRDP.Domain.Entities.FolderEntry", b =>
                {
                    b.HasBaseType("JustRDP.Domain.Entities.TreeEntry");

                    b.Property<string>("CredentialDomain")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CredentialPasswordEncrypted")
                        .HasColumnType("BLOB");

                    b.Property<string>("CredentialUsername")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExpanded")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Folder");
                });

            modelBuilder.Entity("JustRDP.Domain.Entities.TreeEntry", b =>
                {
                    b.HasOne("JustRDP.Domain.Entities.FolderEntry", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("JustRDP.Domain.Entities.FolderEntry", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
